### ISSUE TITLE
Creating an issue fails if inputs.issue_labels is not given

### ISSUE THREAD

**Issue by oke-py** [oke-py/npm-audit-action#15]
**What happened**:
Creating an issue fails if inputs.issue_labels is not given

**What you expected to happen**:
Action is expected to create an issue without labels.

**How you configured .github/workflows/**:
```yaml
name: npm audit

on:
  schedule:
    - cron: '40 * * * *'

jobs:
  scan:
    name: npm audit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: install dependencies
        run: npm ci
      - uses: oke-py/npm-audit-action@v0.1.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue_assignees: oke-py
          issue_lables: vulnerability,test
```
This includes a typo issue_lables.

**Anything else we need to know?**:
