### ISSUE TITLE
Markdown format report

### ISSUE THREAD

**Issue by djereg** [oke-py/npm-audit-action#201]
**What would you like to be added**:
Add mardown output format.
https://gitlab.com/engrave/npm-audit-markdown

**Why is this needed**:
The report looks better then the plain text format.

**Comment by oke-py** [comment]
Thanks for the suggestion, @djereg! 🙏

This has been implemented in #376 and released in [v5.3.0](https://github.com/oke-py/npm-audit-action/releases/tag/v5.3.0). You can get a markdown report by setting the new `report_format` input:

```yaml
- uses: oke-py/npm-audit-action@v5.3.0
  with:
    github_token: ${{ secrets.GITHUB_TOKEN }}
    report_format: markdown
```

With `report_format: markdown`, the report posted to issues and PR comments shows a summary line and a table (package, severity, vulnerable versions, advisory links, fix availability) instead of the plain-text output in a code block. Note that it internally runs `npm audit --json`, so the `npm_audit` action output contains the JSON report — see the README for details.

Feedback is welcome!
