### ISSUE TITLE
PowerShell Script Execution Policy Restriction Causing Workflow Failure

### ISSUE THREAD

**Issue by oke-py** [oke-py/npm-audit-action#208]
## Description
The workflow run [#14776524891](https://github.com/oke-py/npm-audit-action/actions/runs/14776524891) failed due to a restrictive PowerShell execution policy. The error log indicates the following issue:

```
Scripts cannot be executed on this system. To fix, run the command below as Administrator in PowerShell and try again: Set-ExecutionPolicy Unrestricted -Scope CurrentUser -Force
```
## Steps to Reproduce
1. Trigger the `build-test` workflow on this repository.
2. Observe the failure in the "Set PowerShell Execution Policy" step.

## Suggested Fix
Add a step in the workflow file `.github/workflows/test.yml` to set the execution policy before running scripts. Example:

```yaml
- name: Set PowerShell Execution Policy
  run: |
    Set-ExecutionPolicy Unrestricted -Scope CurrentUser -Force
  shell: pwsh
```

## Additional Context
- Workflow file: [test.yml](https://github.com/oke-py/npm-audit-action/blob/cbd2433f5c35976eeb0e8797aad4c0756fa9e49c/.github/workflows/test.yml)
- Workflow run: [#14776524891](https://github.com/oke-py/npm-audit-action/actions/runs/14776524891)
- Job ID: 41485899423
