### ISSUE TITLE
Fix EINVAL error when running npm commands on Windows in GitHub Actions

### ISSUE THREAD

**Issue by oke-py** [oke-py/npm-audit-action#212]
The failure is occurring because of the error: spawnSync npm.cmd EINVAL. This typically happens when the command npm.cmd is not recognized or cannot be run correctly in the environment. Here's the analysis and solution:

## Problem Analysis
1. Error Details:
   * The error `spawnSync npm.cmd EINVAL` indicates that the `npm` command could not be executed properly in the Windows environment.
2. Job Configuration:
    * The failing job is running in `windows-latest` (`build-on-windows` or `test-on-windows` steps).
    * The relevant step is:
        ```YAML
        - name: Install dependencies and run all scripts
          run: |
            npm ci
            npm run all
        ```
3. Possible Causes:
    * `npm` is not properly installed or configured in the Windows environment.
    * The `npm.cmd` file is missing or not accessible in the PATH.
4. Environment Setup:
    * The workflow uses `actions/setup-node@v4` to set up Node.js, which should include npm.
    * However, there might be a misconfiguration or a missing PATH update in the environment.

## Solution
To resolve the issue, ensure that `npm` is correctly set up and accessible. Update the workflow file as follows:

### Updated Workflow
```YAML
- name: Ensure npm is installed and accessible
  run: |
    echo "Verifying npm installation..."
    npm --version
    node --version
```
Add this step right after `actions/setup-node@v4` to verify that `npm` and `node` are correctly installed.

### Debugging the PATH
If `npm` is still not recognized, explicitly add its location to the PATH. Update the workflow as follows:

```YAML
- name: Fix npm PATH issue on Windows
  if: runner.os == 'Windows'
  run: |
    echo "Fixing npm PATH..."
    SET PATH=%APPDATA%\npm;%PATH%
```

### Retry Dependency Installation
If the above steps fix the issue, the `npm ci` and `npm run all` commands should succeed. Ensure these commands are rerun:

```YAML
- name: Re-run Install dependencies and scripts
  run: |
    npm ci
    npm run all
```

## Validation
After applying the fix, re-run the workflow and verify that the job completes without the `EINVAL` error.
