### ISSUE TITLE
Add wildcard and array support for the working_directory input

### ISSUE THREAD

**Issue by dominikfoldi** [oke-py/npm-audit-action#72]
**What would you like to be added**:

It would be great to provide a wildcard pattern and an array of working directories to the `working_directory` input. Then the auditing would run in multiple directories and would add the report in one comment or in multiple comments.

**Why is this needed**:

We have a monorepo and use Lerna to manage it. We have multiple packages in multiple directories like `packages` and `tools`. Right now it would be a long list of steps in the workflow if we would want to configure every one of our packages to be audited by this action, plus every time when we add a new package, we would have to add a new step to have that package audited too.

**Suggested input format**:

```yml
 with:
  working_directory: |
    packages/*
    tools/*
```

**Comment by oke-py** [comment]
Closing with a documented alternative rather than implementing glob/array support.

The monorepo use case is legitimate, but GitHub Actions already has a first-class answer for "run the same job over N directories": a [job matrix](https://docs.github.com/en/actions/using-jobs/using-a-matrix-for-your-jobs). Handling globbing and multi-report aggregation inside the action would duplicate that machinery with more complexity and less flexibility (matrix gives you parallelism, per-package pass/fail status, and `fail-fast` control for free).

The README now documents the pattern (#378):

```yaml
jobs:
  scan:
    strategy:
      matrix:
        workdir: [packages/a, packages/b, tools/c]
    steps:
      # checkout, npm ci ...
      - uses: oke-py/npm-audit-action@v5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          working_directory: ${{ matrix.workdir }}
          issue_title: 'npm audit found vulnerabilities (${{ matrix.workdir }})'
          dedupe_issues: true
```

Including the directory in `issue_title` keeps `dedupe_issues` working per package. New packages can be picked up by generating the matrix from a `find`/`ls` step if desired.
